// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.imyeego.protobuf;

public interface UserOrBuilder extends
    // @@protoc_insertion_point(interface_extends:User)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   *ID
   * </pre>
   *
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   *姓名
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();
}
